stat_xilinx ./SubModules/AES_Comp.v
stat_xilinx ./SubModules/AES_Comp_DEC.v
stat_xilinx ./SubModules/AES_Comp_DecCore.v
stat_xilinx ./SubModules/AES_Comp_ENC.v
stat_xilinx ./SubModules/AES_Comp_EncCore.v
stat_xilinx ./SubModules/AES_Comp_GFinvComp.v
stat_xilinx ./SubModules/AES_Comp_InvMixColumns.v
stat_xilinx ./SubModules/AES_Comp_InvSboxComp.v
stat_xilinx ./SubModules/AES_Comp_InvSubBytesComp.v
stat_xilinx ./SubModules/AES_Comp_MixColumns.v
stat_xilinx ./SubModules/AES_Comp_SboxComp.v
stat_xilinx ./SubModules/AES_Comp_SubBytesComp.v
